# 10/052021
guests = ["Phoebe", "Maya", "Tanya"]
message = ("I would like to invite you to dinner.")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print ("\nMaya cant make it.")
guests[1] = ("Shona")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print ("\nI found a bigger table, so I am inviting 3 more guests.")
guests.insert(1,"Hosina")
guests.insert(2,"Ria")
guests.append("Anika")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print (f"Hello {guests[3]}, {message}")
print (f"Hello {guests[4]}, {message}")
print (f"Hello {guests[5]}, {message}")
print ("\nThe new dinner table won't arrive in time so I can only invite two guests.")
sorry_message = ("I won't be able to invite you to the dinner.")
removed_guest = guests.pop(1)
print (f"Sorry {removed_guest}, {sorry_message}")
removed_guest = guests.pop(1)
print (f"Sorry {removed_guest}, {sorry_message}")
removed_guest = guests.pop(2)
print (f"Sorry {removed_guest}, {sorry_message}")
removed_guest = guests.pop(2)
print (f"Sorry {removed_guest}, {sorry_message}")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print ("\nThe number nuber of guests invited for dinner is :")
print (len(guests))