# 10/052021
guests = ["Phoebe", "Maya", "Tanya"]
message = ("I would like to invite you to dinner.")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print ("\nMaya cant make it.")
guests[1] = ("Shona")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print ("\nI found a bigger table, so I am inviting 3 more guests.")
guests.insert(1,"Hosina")
guests.insert(2,"Ria")
guests.append("Anika")
print (f"Hello {guests[0]}, {message}")
print (f"Hello {guests[1]}, {message}")
print (f"Hello {guests[2]}, {message}")
print (f"Hello {guests[3]}, {message}")
print (f"Hello {guests[4]}, {message}")
print (f"Hello {guests[5]}, {message}")