locations = ['Paris', 'Korea', 'China', 'Japan', 'Canada']
print (locations)
print (sorted(locations))
print (locations)
print ("\n", sorted(locations, reverse=True))
print (locations)
locations.reverse()
print ("\n", locations)
locations.reverse()
print ("\n", locations)
locations.sort()
print ("\n", locations)
locations.sort(reverse=True)
print ("\n", locations)